### ISSUE TITLE
Mismatched API version

### ISSUE THREAD

**Issue by ams0** [Azure/OpenShift#100]
I used to be able to create clusters but seems something is off:

```
$> az openshift create --resource-group openshiftme --name openshiftme -l eastus

No registered resource provider found for location 'eastus' and API version '2019-04-30' for type 'openShiftManagedClusters'. The supported api-versions are '2018-09-30-preview'. The supported locations are 'eastus, eastus2, westus, westus2, westcentralus, southcentralus, centralus, westeurope, northeurope, uksouth, ukwest, francecentral, canadaeast, canadacentral, australiaeast, australiasoutheast, eastasia, southeastasia'.
```

I have az-cli 2.0.64 and Microsoft.ContainerService/OpenshiftManagedCluster is registered.

**Comment by charlesakalugwu** [comment]
Hi Alessandro,

I wasn't able to reproduce your issue. I was able to create a cluster in the `eastus` region using az cli `2.0.64` (logs to follow later). Out of curiosity are you using the native az cli or are you using some form of containerized cli as we used to during the private preview? If yes, you might want to run a `docker pull` beforehand. Furthermore, do you consistently hit this issue? Or was it just a one-off?


*az cli version*
```
[charles@akalugwu ~]$ az --version
azure-cli                         2.0.64

-- the rest omitted for brevity --
```

*create rg*
```
[charles@akalugwu ~]$ az group create --name charles-test-vozza-az64 --location eastus
{
  "id": "/subscriptions/xxxxxx/resourceGroups/charles-test-vozza-az64",
  "location": "eastus",
  "managedBy": null,
  "name": "charles-test-vozza-az64",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": null
}
```

*create cluster*
```
[charles@akalugwu ~]$ az openshift create --resource-group charles-test-vozza-az64 --name charles-test-vozza-az64  -l eastus 
[charles@akalugwu ~]$ az openshift show --name charles-test-vozza-az64 -g charles-test-vozza-az64 | jq '.provisioningState'
"Succeeded"
```

**Comment by ams0** [comment]
Thanks, I have the same from Azure shell too. Which docker image should I use?

**Comment by charlesakalugwu** [comment]
@ams0 I don't think it is recommended to use the docker image now that we are out of private preview. 

@julienstroheker do you have any ideas whats going on here?

**Comment by julienstroheker** [comment]
@ams0 your msg from the cli is by design.

GA API is activated when the OpenShift license is purchased: https://azure.microsoft.com/en-us/services/openshift/
