### ISSUE TITLE
How is logging and aggregated logging handled currently ?

### ISSUE THREAD

**Issue by mattvbv** [Azure/OpenShift#104]
I have a cluster running with some applications. How can I get a solution equivalent than the one I have in a self installed OpenShift cluster such as Elastic/Fluentd/Kibana (EFK) ? 

I haven't seen anything in the documentation or in the roadmap.

Thanks,

M.

**Comment by mattvbv** [comment]
I found some information in the FAQ stating that the customer does not have access to docker logs, so the solution based on EFK will not be possible.
I also looked in the default log analytics workspace, I don't see any log related to the managed OpenShift cluster.

**Comment by charlesakalugwu** [comment]
@mattvbv we are currently working on ARO integration with Azure Monitor. After that lands, you should be able to see your workload telemetry (logs and metrics) in the log analytics workspace you specified during ARO cluster creation. Barring unforeseen hindrances, we believe this integration will graduate to private preview at the start of October 2019.

**Comment by sakthi-vetrivel** [comment]
@mattvbv ARO is now integrated with Azure Monitor. Please see the docs here: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-azure-redhat4-setup
