### ISSUE TITLE
Wrong documentation for internal Load Balancers

### ISSUE THREAD

**Issue by robinmanuelthiel** [Azure/OpenShift#108]
Not sure, if this is the right place for documentation feedback on the Red Hat side, but the [docs for creating an internal load balancer](https://docs.openshift.com/aro/getting_started/access_your_services.html#create-an-internal-only-tcp-service) have a mistake!

Instead of `service.beta.kubernetes.io/azure-load-balancer-internal: 0.0.0.0/0` it should be `service.beta.kubernetes.io/azure-load-balancer-internal: \"true\"`.

The requested change ist moving from this

```bash
$ oc expose dc httpd-example --type=LoadBalancer --name=internal-lb --dry-run -o yaml | awk '1;/metadata:/{ print "  annotations:\n    service.beta.kubernetes.io/azure-load-balancer-internal: 0.0.0.0/0" }' | oc create -f -
service/internal-lb exposed
```

to that

```bash
$ oc expose dc httpd-example --type=LoadBalancer --name=internal-lb --dry-run -o yaml | awk '1;/metadata:/{ print "  annotations:\n    service.beta.kubernetes.io/azure-load-balancer-internal: \"true\"" }' | oc create -f -
service/internal-lb exposed
```

If this is not the right place for that kind of feedback, can someone point me to the correct feedback channel?

**Comment by jim-minter** [comment]
@robinmanuelthiel thanks for the feedback - you're right.  @Makdaam please can you open a PR to fix this in https://github.com/openshift/openshift-docs ?

**Comment by Makdaam** [comment]
Thanks for the report @robinmanuelthie, the docs should be fixed soon.

**Comment by amanohar** [comment]
Closing as documentation has been fixed.

**Comment by robinmanuelthiel** [comment]
When do you expect it to go live?

**Comment by Makdaam** [comment]
It just got merged and published.
