### ISSUE TITLE
GPU support for ARO - Batch 1

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/OpenShift#193]
Today, ARO does not support GPU-enabled worker nodes for an ARO cluster. This issue tracks support for them as ARO worker nodes.

NC4as T4 v3
NC8as T4 v3
NC16as T4 v3
NC464as T4 v3

**Comment by waynedovey** [comment]
Is there any moment on this? We are seeing a lot of requirements to have this feature available. Thanks

**Comment by git2g** [comment]
Is there an ETA on when this will be in public preview?

**Comment by philipp1992** [comment]
any news on this?

**Comment by supernovae** [comment]
Any update on this?

**Comment by rahulm23** [comment]
We are treating this request as part of two milestones. First milestone will require more steps on part of customers to configure. At the moment it is targeted for Q1 2022. Regarding 2nd milestone, it will be a better experience and will share the ETA once we get closer.

**Comment by msftnadavbh** [comment]
Any updates?

**Comment by philipp1992** [comment]
Just use aks

**Comment by stuartatmicrosoft** [comment]
If you require this capability in ARO, please reach out to me.  Thank you.

**Comment by philipp1992** [comment]
Yes we do.I guess that's the reason people come to this issue.

**Comment by supernovae** [comment]
I wrote up a guide to implementing GPU on ARO - https://mobb.ninja/docs/aro/gpu/  - Documentation is in progress.

**Comment by jboutaud** [comment]
The instance types planned for support are the following: 
NC4as T4 v3
NC8as T4 v3
NC16as T4 v3
NC464as T4 v3

**Comment by jboutaud** [comment]
This is now officially supported. Here is a reference to the article explaining how to use GPUs: https://docs.microsoft.com/en-us/azure/openshift/howto-gpu-workloads

**Comment by maulik-modi22** [comment]
These `T4` GPUs may not be suitable for heavy duty training workload.....

We require Tesla V100 or Nvidia A10 GPU support, eagerly awaiting for  #276
