### ISSUE TITLE
Egress Lockdown

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/OpenShift#194]

**Comment by cosmos0703** [comment]
Hello all Can I know when this function will be preview? 
And if this function comes out,   can we connect to azure firewall for outbound connection of Azure Openshift service?
Or can we connect outbound flow to azure firewall even if this function is not ga?(like this document : https://github.com/akamenev/aro-private)
Thanks

**Comment by jboutaud** [comment]
We have implemented a privatelink ARO service which provides access to mandatory resources for a cluster to function. details around how Egress Lockdown works can be found here: 
https://learn.microsoft.com/en-us/azure/openshift/concepts-egress-lockdown
