### ISSUE TITLE
Why do we have to create a Red Hat OpenShift Image pull secret manually for ARO ?

### ISSUE THREAD

**Issue by jomeier** [Azure/OpenShift#200]
Hi,

we are using ARO 4.5 and I'm wondering why we have to create an Red Hat image pull secret manually on 

https://cloud.redhat.com

before we can use Red Hat operators as OpenShift Service Mesh, Tekton Pipelines, OpenShift Serverless.

Aren't this operators included in ARO?

As far as I know the Red Hat image pull secrets are only valid for 60 days (trial!).

Thank you and greetings,

Josef

**Comment by sakthi-vetrivel** [comment]
Hi @jomeier, we do this because we need separate authentication process to get to the Red Hat registry. This is something we can look into changing by updating how we track customer entitlements and registering clusters.
