### ISSUE TITLE
BYOK for OS disks

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/OpenShift#206]
Support encryption of OS disks with customer managed keys.

**Comment by stuartatmicrosoft** [comment]
Is this in public preview? I know that BYOK for PVC is in public preview as I created the initial documentation for the process.  That said, BYOK for master/worker node OS disk encryption I understood to be further out?

**Comment by jboutaud** [comment]
Cleaning the board, closing this item this was delivered November 2021:  https://learn.microsoft.com/en-us/azure/openshift/howto-byok#create-an-azure-key-vault-instance
