### ISSUE TITLE
Ephemeral OS disk

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/OpenShift#211]
The issue tracks support for choosing an ephemeral OS disk for your agent nodes in an ARO cluster. This provides lower read/write latency, along with faster node scaling and cluster upgrades.

**Comment by 0kashi** [comment]
Supported as a "day 2" configuration for worker nodes. [https://docs.openshift.com/container-platform/latest/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-azure-ephemeral-os_creating-machineset-azure](https://docs.openshift.com/container-platform/latest/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-azure-ephemeral-os_creating-machineset-azure)
