### ISSUE TITLE
Add Azure Disk CSI Drivers

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/OpenShift#216]
https://docs.openshift.com/container-platform/4.10/storage/container_storage_interface/persistent-storage-csi-azure.html

**Comment by ezYakaEagle442** [comment]
Azure File CSI driver is now GA.

**Comment by TiloGit** [comment]
Great idea, how can we check if Azure CSI Drivers are loaded/used in ARO?

**Comment by andyzhangx** [comment]
@TiloGit
```console
# kubectl get po --all-namespaces | grep csi
kube-system   csi-azuredisk-controller-77d5ccd444-4gf2h   5/5     Running   14         8d
kube-system   csi-azuredisk-node-prt5d                    3/3     Running   0          8d
kube-system   csi-azurefile-controller-7c7bb9474c-6l7p5   0/5     Pending   0          13d
kube-system   csi-azurefile-controller-7c7bb9474c-bc7nl   5/5     Running   32         13d
kube-system   csi-azurefile-node-4b67t                    3/3     Running   0          13d
```

**Comment by ezYakaEagle442** [comment]
@sakthi-vetrivel  @kagowda

**Comment by ezYakaEagle442** [comment]
@rahug1190 could you please tag this in thge roadmap ?

**Comment by ezYakaEagle442** [comment]
docs at : 

[https://docs.openshift.com/container-platform/4.9/storage/persistent_storage/persistent-storage-azure-file.html](https://docs.openshift.com/container-platform/4.9/storage/persistent_storage/persistent-storage-azure-file.html)

[https://docs.microsoft.com/en-us/azure/openshift/howto-create-a-storageclass](https://docs.microsoft.com/en-us/azure/openshift/howto-create-a-storageclass)

**Comment by jboutaud** [comment]
Support for Azure Disk CSI driver was delivered as part of Openshift 4.10. For latest documentation, please go here: https://docs.openshift.com/container-platform/4.11/storage/container_storage_interface/persistent-storage-csi-azure.html
