### ISSUE TITLE
ARO Private Cluster with 120 Nodes

### ISSUE THREAD

**Issue by jboutaud** [Azure/OpenShift#247]
ARO's current maximum is 60 worker nodes, would like to support having more worker nodes

**Comment by pittar** [comment]
@jboutaud , I hear UDR is now GA and should allow for larger clusters.  Is this true?  If so, what would the new max be?

**Comment by konghot** [comment]
ARO public docs will be updated very soon.

**Comment by konghot** [comment]
https://learn.microsoft.com/en-us/azure/openshift/openshift-faq#what-is-the-maximum-number-of-pods-in-an-azure-red-hat-openshift-cluster---what-is-the-maximum-number-of-pods-per-node-in-azure-red-hat-openshift
