### ISSUE TITLE
Release 4.10

### ISSUE THREAD

**Issue by jboutaud** [Azure/OpenShift#267]
Make OCP 4.10 the default version at Install time

**Comment by wjurmy** [comment]
@jboutaud Any estimation for releasing this feature?

**Comment by diskmanti** [comment]
Hello @jboutaud,

Is there an ETA for the 4.10 release?

Thank you

**Comment by supernovae** [comment]
4.10 has been released for ARO

**Comment by jboutaud** [comment]
yes, ARO 4.10 is now live in all regions.

**Comment by maulik-shah999** [comment]
@jboutaud @supernovae Can someone from your team help on this issue? https://github.com/Azure/OpenShift/issues/286
