### ISSUE TITLE
No Public IP in private clusters - UserDefinedRouting

### ISSUE THREAD

**Issue by jboutaud** [Azure/OpenShift#272]
A private ARO cluster has a public IP deployed to ensure that clusters can reach out to mandatory resources for the cluster to be functional. That public IP is configured in such a way that no ingress is possible however, customer who are routing traffic through their internal network or are security conscious do not want the public IP to be there at all. 

This request is to provide customers the ability to have a flag at install time which will result in the cluster being deployed without a public IP.

**Comment by jboutaud** [comment]
Preview for this feature is now available. Customers can register for the feature through the documentation available at this link: https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x

**Comment by krzgar** [comment]
Is there an estimate on when this feature will be Globally Available?

**Comment by konghot** [comment]
https://learn.microsoft.com/en-us/cli/azure/aro?view=azure-cli-latest#az-aro-create()-optional-parameters

--outbound-type
