### ISSUE TITLE
Documentation for KeyVault w/ARO

### ISSUE THREAD

**Issue by 0kashi** [Azure/OpenShift#275]
Publish documentation on how to enable the use of KeyVault with ARO clusters

**Comment by dsanchor** [comment]
Any ETA for this feature?

**Comment by andremmandrade** [comment]
hello team any ETA on this feature?

**Comment by konghot** [comment]
It is recommended to use Azure ARC with Keyvault extension, pointing to an ARO cluster (since ARC already supports Openshift clusters), to use Keyvault seamlessly with ARO clusters.

https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-akv-secrets-provider
