### ISSUE TITLE
GPU worker nodes - Batch 2

### ISSUE THREAD

**Issue by 0kashi** [Azure/OpenShift#276]
Support for the following GPU nodes as worker nodes:

Standard_NC6s_v3
Standard_NC12s_v3
Standard_NC24s_v3
Standard_NC24rs_v3

**Comment by fc7** [comment]
@0kashi According to https://learn.microsoft.com/en-us/azure/openshift/howto-gpu-workloads the types mentioned in the description above are now supported. Hence my question: is this ticket still relevant?

**Comment by maulik-modi22** [comment]
@0kashi, I have the same question as fc7, Is this ticket still relevant?

https://learn.microsoft.com/en-us/azure/openshift/howto-gpu-workloads mentions
> ARO supports the following GPU workers:
NC4as T4 v3
NC6s v3
NC8as T4 v3
NC12s v3
NC16as T4 v3
NC24s v3
NC24rs v3
NC64as T4 v3
