### ISSUE TITLE
Enhancements to AzureRM Terraform Provider for ARO Clusters

### ISSUE THREAD

**Issue by 0kashi** [Azure/OpenShift#282]

**Comment by sandole** [comment]
Avanade waiting for this feature.

JSON encode does not work really well. :(

**Comment by bartek-lopatka** [comment]
Can we have ETA on that, please? :)

**Comment by qazimobeen** [comment]
Hi @konghot and @0kashi - are we progressing on it further? What other alternative do exist for this?

Shall we fallback on Ansible way of working?

**Comment by BenjaminNeale-Heritage** [comment]
I'm interested to know what this will offer as we hope to start using Terraform to automate our ARO cluster provisioning in the next couple of months.
