### ISSUE TITLE
az feature register step documentation is unclear

### ISSUE THREAD

**Issue by jim-minter** [Azure/OpenShift#29]
When I run `az feature register --namespace Microsoft.ContainerService -n openshiftmanagedcluster` I get the message `Once the feature 'openshiftmanagedcluster' is registered, invoking 'az provider register -n Microsoft.ContainerService' is required to get the change propagated`.

When I then run `az provider register -n Microsoft.ContainerService` I get the message `Registering is still on-going. You can monitor using 'az provider show -n Microsoft.ContainerService'`.  (note the erroneous trailing quote in the error message).

When I then run `az provider show -n Microsoft.ContainerService`, it shows `"registrationState": "Registered"`, but if I retry the previous steps I get the same messages as before.  How do I know when the process is done?

Also, do I need to run some feature or provider registration process for Microsoft.Solutions?

**Comment by amanohar** [comment]
Registering `Microsoft.Solutions` is needed. It's documented here: https://github.com/Azure/OpenShift/pull/23

I will follow up on the other issue and add updates here.

**Comment by jim-minter** [comment]
sorry, I think I should read the doc

**Comment by amanohar** [comment]
@jim-minter for the first issue. I followed up with the CLI/SDK team. They will fix it to not return `Registering is still on-going...` message if RP has already been registered.
