### ISSUE TITLE
Release ARO 4.12 as an install time option

### ISSUE THREAD

**Issue by khensel17** [Azure/OpenShift#300]

**Comment by khensel17** [comment]
Can someone give an estimate when Openshift 4.12 will be available?

**Comment by jboutaud** [comment]
Hi @khensel, 
Upgrades to 4.12 are available today if you are looking for 4.12. We are currently working on making 4.12 available at install, it's still a little bit out but it's active right now. 

Thanks,
Jerome

**Comment by khensel17** [comment]
Hi @jboutaud,

According to the support lifecycle documentation https://learn.microsoft.com/en-us/azure/openshift/support-lifecycle#azure-red-hat-openshift-release-calendar upgrades to Openshift 4.12 aren't supported yet. Can you ellaborate when this will be the case?

**Comment by BenjaminNeale-Heritage** [comment]
I would also like to know when OCP 4.12 will be fully supported within ARO.  OCP 'allows' for upgrades to OCP 4.12 within ARO but this will put the cluster into an 'out of support' state based on the ARO Support Lifecycle page linked earlier.  Being in an 'out of support' state is not an acceptable option at my company and it defeats the purpose of using a managed PaaS offering.

@jboutaud ... If upgrades to OCP 4.12 are supported on ARO even while new installs of OCP 4.12 are not yet supported then can someone at Microsoft please update the ARO Support Lifecycle page to clearly state this situation?

**Comment by JPrice904** [comment]
> I would also like to know when OCP 4.12 will be fully supported within ARO. OCP 'allows' for upgrades to OCP 4.12 within ARO but this will put the cluster into an 'out of support' state based on the ARO Support Lifecycle page linked earlier. Being in an 'out of support' state is not an acceptable option at my company and it defeats the purpose of using a managed PaaS offering.
> 
> @jboutaud ... If upgrades to OCP 4.12 are supported on ARO even while new installs of OCP 4.12 are not yet supported then can someone at Microsoft please update the ARO Support Lifecycle page to clearly state this situation?

Seconded this - need better understanding of what is and what isn't supported as the ARO life cycle page and Red Hat's own lifecycle page make things even more confusing too.

Per the [FAQ](https://learn.microsoft.com/en-us/azure/openshift/support-lifecycle#faq)

" A version is supported as soon as an upgrade path to that version is available. "

So does this mean because OCP 4.12 is a viable upgrade path from 4.11 we would get support or should we follow the matrix and assume that only 4.11 is supported at this time until it's GA by MS?  If it's a viable upgrade path and supported would that mean clusters running OCP 4.10 are now out of support?

**Comment by jboutaud** [comment]
@jprice904,
Thanks for the feedback. We will look at updating and making things clearer when we update the documents as part of making 4.12 available at install time and expanding the lifecycle but let me try to explain to make it clear before we update the documents: 

To clarify your question, an example:  
**Today:**
4.10,4.11 are available at install time and are fully supported.
4.12 is fully supported as you can upgrade from 4.11 to 4.12 
4.13 is not as there is no upgrade path to 4.13 at the moment 

Once an upgrade path to 4.13 is available then it will be fully supported as well

**As far as EOL,** 
Today: 
EOL of a version (4.10) is 30 days after we make N+2 available, 4.12 in this case
Future:
Starting with 4.12, we will be moving to a 14 month support cycle which starts when we make that version available at install time so if 4.12 was made available today at install time (June 22), EOL would be Aug 22 2024. 

I hope this helps clarify things until our documentation is updated as part of the 4.12 launch.

**Comment by BenjaminNeale-Heritage** [comment]
Thanks @jboutaud.  That helps clarify the situation. 😄 It would be a pain to try to explain this situation to compliance staff but I'm glad that the documentation will be improved also to make the support situation clearer.

**Comment by davidkarlsen** [comment]
Shouldn't this be closed as fixed?

**Comment by jboutaud** [comment]
Thanks for point this out. We moved it to done category but didn't close the card. Closing as we have made 4.12 available to customers at install time.
