### ISSUE TITLE
Openshift 4.15 ARO support - Install target

### ISSUE THREAD

**Issue by khensel17** [Azure/OpenShift#317]
Is there an ETA when ARO 4.15 is supported and available at install time?

**Comment by mayurigupta13** [comment]
It is available for upgrade and is supported. This issue is scoped to 'Install target availability' now.

**Comment by FischerLGLN** [comment]
We use the Azure ARO version ‘4.14.16’ to restore the ARO cluster via Terraform after a loss of the cluster. Restoring to a newer version such as 4.15.x or 4.16.x is not directly possible and would take one hour per version jump after reinstallation of 45 minutes.

**Comment by khensel17** [comment]
At this moment Openshift version 4.15.27 is available at install time.
