### ISSUE TITLE
Don't allow changing AAD app id, secret, or tenant during update call

### ISSUE THREAD

**Issue by julienstroheker** [Azure/OpenShift#39]
Validate that an update/scale operation with different/changed AAD Auth profile values is not allowed.

**Comment by amanohar** [comment]
@mjudeikis @jim-minter, customer being able to change AAD auth profile parameters: is this expected behavior?

**Comment by mjudeikis** [comment]
I dont see a reason why in a long run it should not be able to do so. But for initial GA I think we need to make sure it can't be done it. It will cause node rotation, and an update to happen. Tempted to make sure we open this configurable later in the product lifecycle. 
Needs @jim-minter input on this.

**Comment by amanohar** [comment]
@julienstroheker IIRC you were able to rotate the creds? Can you confirm what you observed?

**Comment by julienstroheker** [comment]
Yes i was able to rotate the creds, cluster was working,  but got a timeout answer from the RP.

**Comment by mjudeikis** [comment]
@julienstroheker can you elaborate on this?

**Comment by sakthi-vetrivel** [comment]
Closing this issue as it's gone stale.
