### ISSUE TITLE
Add `LinkedAuthorizationFailed` error to known issues page

### ISSUE THREAD

**Issue by amanohar** [Azure/OpenShift#41]
First time OSA cluster creator customer might run into the following error. This error should happen the first time a subscription tries to create an OSA cluster.

```
{
 "code": "LinkedAuthorizationFailed",
 "message": "The client has permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on scope '/subscriptions/<SUBID>/resourcegroups/<RGNAME>/providers/Microsoft.Compute/virtualMachineScaleSets/ss-compute', however the current tenant '<TENANTID>' is not authorized to access linked subscription '<SUBID>'."
}
```

_Recommended mitigation:_ Customer should wait 10 mins and try creating a new cluster.

**Comment by sozercan** [comment]
@amanohar is this still an issue?

**Comment by hasnas** [comment]
@sozercan Just had the same issue trying to deploy a template containing a single alert.
