### ISSUE TITLE
Create Process not Accepting Passed in Azure Tenant ID

### ISSUE THREAD

**Issue by kevingbb** [Azure/OpenShift#46]
Passing in app registration credentials from a newly created Azure AD Tenant that is not the default Azure Tenant associated with the Subscription fails.

I created a new Azure AD Tenant so I could control all App Registrations. I then created a New App Registration in the new tenant. I used the newly created App Registration details and new Azure AD Tenant ID in the az openshift create command. After the Cluster was provisioned and tried to sign in to the Open Shift Cluster using an ID from the newly created Azure AD Tenant, it errored saying it could not find the App Registration in Tenant X where Tenant X was the default Azure AD Tenant associated with the Subscription versus the newly created Azure AD Tenant.

**Comment by julienstroheker** [comment]
@kevingbb Please give it another try and let me know if you still have the same issue? Thanks.

**Comment by kevingbb** [comment]
Connecting to an Azure AD Tenant that is not the default one attached to the Subscription is now working.
