### ISSUE TITLE
Need admin approval - Authentication

### ISSUE THREAD

**Issue by julienstroheker** [Azure/OpenShift#47]
Seems Azure changed their policy to use the following permissions : 
`Windows Azure Active Directory` - `Sign in and read user profile`

This cause a `Need admin approval` message at the first authentication into the cluster using Azure AD Authentication method.

![aaderrorauth](https://user-images.githubusercontent.com/8661347/47447537-c2987f00-d78b-11e8-8b98-eb5503b050da.png)

**Comment by amanohar** [comment]
@julienstroheker it's not Azure that changes the policy, it's the AAD tenant admin. So this error is going to be dependent on a customer's organization's AAD tenant policies.

**Comment by wenboyang214** [comment]
log in with admin account and click accept button. You can find a useful link [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/application-consent-experience)
