### ISSUE TITLE
Can't recreate cluster with same resourcegroup

### ISSUE THREAD

**Issue by thekad** [Azure/OpenShift#49]
Previously I had created a cluster named `kadosaprod` (in a RG named the same) using `az openshift create`. I destroyed it using `az openshift delete` and also removed the RG (and all traces I could find of resources created by said cluster) but I can't seem to re-create the cluster in a similarly named RG. `az openshift create` chugs along for a while but I get an error at the end, here's the debug output:

```
msrest.exceptions : Creating customer service principal failed. Detail: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2018-12-03T16:37:03","message":{"lang":"en","value":"Another object with the same value for property identifierUris already exists."},"requestId":"ae79af44-422b-4f2f-966e-59c213209522","values":[{"item":"PropertyName","value":"identifierUris"},{"item":"PropertyErrorCode","value":"ObjectConflict"}]}}]
Deployment failed. Correlation ID: d4df04e6-e072-48e5-a440-e7b335d931a1. Creating customer service principal failed. Detail: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2018-12-03T16:37:03","message":{"lang":"en","value":"Another object with the same value for property identifierUris already exists."},"requestId":"ae79af44-422b-4f2f-966e-59c213209522","values":[{"item":"PropertyName","value":"identifierUris"},{"item":"PropertyErrorCode","value":"ObjectConflict"}]}}]
```

cc @julienstroheker @amanohar

**Comment by julienstroheker** [comment]
@thekad I have to double check but I think this come from the app object that the cli is auto generating during the creation of the cluster.

Did you provide your own App ID and Secret during the creation ?

**Comment by thekad** [comment]
@julienstroheker no, in this case I let it create its own app credentials

**Comment by julienstroheker** [comment]
Thanks @thekad 

I'll check, we are supposed to updated the current existing app instead of creating a new one (which already exists) since we are not deleting it during the `az openshift delete` command.

We are not supposed to have a `graphrbac.ApplicationsClient#Create` error.

Thanks for reporting this.
