### ISSUE TITLE
How to use already existing Azure AD App when creating openshift cluster?

### ISSUE THREAD

**Issue by hyundonk** [Azure/OpenShift#53]
Customer got error message below when creating openshift cluster.
az openshift create --resource-group $CLUSTER_NAME --name $CLUSTER_NAME -l $LOCATION --fqdn $FQDN
Directory permission is needed for the current user to register the application. For how to configure, please refer 'https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal'. Original error: Insufficient privileges to complete the operation.

Customer doesn't have privilege to register AD app and have to ask Azure AD admin to do that. 
How can customer create openshift cluster  with existing AD App?

Thank you!

**Comment by julienstroheker** [comment]
Hi @hyundonk 

You should be able to create a cluster using the cli and  the `--aad-client-app-id` `--aad-client-app-secret` and `--aad-client-app-tenant` flag.

```
az openshift create -g MyResourceGroup -n MyManagedCluster --fqdn <FQDN> --aad-client-app-id <APP_ID> --aad-client-app-secret <APP_SECRET> --aad-tenant-id <TENANT_ID>
```

**Comment by hyundonk** [comment]
Thank you very much Julien!
