### ISSUE TITLE
How do we report OSA installation issues?

### ISSUE THREAD

**Issue by dcfsc** [Azure/OpenShift#54]
Follett is previewing OSA and I have some feedback on installation issues. 

Do we just add issues here or on openshift-azure-discuss? This is not clear from the doc.

**Comment by julienstroheker** [comment]
Hi @dcfsc 

If it is just question `openshift-azure-discuss` is the best place, if it is issue / bug here could be a good place to start to keep a track of it.

Hope it makes sense ? 

Thanks
