### ISSUE TITLE
create: FQDN provided is not used; new cluster unavailable

### ISSUE THREAD

**Issue by dcfsc** [Azure/OpenShift#56]
Creating a new cluster
```
CLUSTER_NAME=fssocpdemo
RESOURCE_GROUP_NAME=prdusefssocpdemorg
LOCATION=eastus
FQDN=$CLUSTER_NAME.$LOCATION.cloudapp.azure.com
# az openshift create --resource-group $RESOURCE_GROUP_NAME --name $CLUSTER_NAME -l $LOCATION --fqdn $FQDN
```

After creation try to access the new cluster

```
$ ping prdusefssocpdemorg.eastus.cloudapp.azure.com
ping: prdusefssocpdemorg.eastus.cloudapp.azure.com: Name or service not known
```

So the dns name is invalid.

FQDN in the return JSON has a valid DNS name.
```
 "routerProfiles": [
    {
      "fqdn": "osab882XXXXXXX.eastus.cloudapp.azure.com",
      "name": "default",
      "publicSubdomain": "197bff743daXXXXXX.eastus.azmosa.io"
    }
```
Now use the fqdn value:

```
curl -k  -v https://osab882XXXXXXX.eastus.cloudapp.azure.com
* About to connect() to osab882XXXXXXX.eastus.cloudapp.azure.com port 443 (#0)
*   Trying 137.135.107.111...
* Connected to osab882XXXXXXX.eastus.cloudapp.azure.com (137.135.107.111) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=197bff743daXXXXXX.eastus.azmosa.io
*       start date: Jan 04 13:33:25 2019 GMT
*       expire date: Jan 04 13:33:25 2021 GMT
*       common name: 197bff743daXXXXXX.eastus.azmosa.io
*       issuer: CN=openshift-signer
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: osab882XXXXXXX.eastus.cloudapp.azure.com
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 503 Service Unavailable
```
The OSA console is not available at this location.

![image](https://user-images.githubusercontent.com/4459911/50706012-34aa0180-1022-11e9-9ffc-2b85c0203f25.png)

**Comment by julienstroheker** [comment]
Hi @dcfsc 

You should be redirected to the console by entering this fqdn using https in your browser : `https://osab882XXXXXXX.eastus.cloudapp.azure.com`

Worst case you can try : `https://osab882XXXXXXX.eastus.cloudapp.azure.com/console/`

About the ping command, this is a normal behavior, ping is blocked.

**Comment by julienstroheker** [comment]
Do you have any ssl error by trying different browser, you may need to accept the untrusted cert : 

<img width="674" alt="screen shot 2019-01-10 at 12 56 54 pm" src="https://user-images.githubusercontent.com/8661347/50987319-5bab7c00-14d7-11e9-8162-340e50f565bb.png">

Rebuilding a new cluster could also help.

Thanks

**Comment by amanohar** [comment]
@dcfsc are you still running into this error?

**Comment by amanohar** [comment]
Closing as issue has been inactive for a while. Please open a new issue if you are still running into an error.
