### ISSUE TITLE
Microsoft.ContainerService - RegistrationState stays "Pending"

### ISSUE THREAD

**Issue by jimleitch01** [Azure/OpenShift#59]
Hi,

I'm super keen to try out the Managed OpenShift on Azure, but when I take the first step as described:

`Register-AzProviderFeature -ProviderNamespace Microsoft.ContainerService -FeatureName openshiftmanagedcluster`

..I've been checking for about the last 8 hours, but it's still PENDING, and something tells me it isn't going to change any time soon. Any ideas ?? Please let me know if I can provide any further information.

```PS Azure:\> Get-AzureRmProviderFeature -ProviderNamespace Microsoft.ContainerService -FeatureName openshiftmanagedcluster

FeatureName             ProviderName               RegistrationState
-----------             ------------               -----------------
openshiftmanagedcluster Microsoft.ContainerService Pending
```

Thanks and regards,

Jim

**Comment by jimleitch01** [comment]
No one answering, perhaps I need to try more options and debugging on my side, will close for now until I have more evidence (or it works)

**Comment by sozercan** [comment]
Hi @jimleitch01,

Managed OpenShift in Azure is in private preview at this time. Is your subscription part of whitelisted group of subs to access the feature?

Thanks!
