### ISSUE TITLE
vnet peering doesn't work when target vnet is under different subscription.

### ISSUE THREAD

**Issue by tahonen** [Azure/OpenShift#68]
Installation failds when vnet to peer is in under different subscription. Tested installation by giving vnet id for vnet that was in under same resource group. Installation worked and vnets were peered. When tried to install with peering to vnet from different subscription, installation failed.

Deployment failed. Correlation ID: xxxxx. Creating virtual network peering failed. Detail: network.VirtualNetworkPeeringsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client 'xxxxxx' with object id 'xxxxx' has permission to perform action 'Microsoft.Network/virtualNetworks/virtualNetworkPeerings/write' on scope '/subscriptions/xxxxxx/resourceGroups/xxxxx/providers/Microsoft.Network/virtualNetworks/vnet/virtualNetworkPeerings/OSAClusterVNetPeer'; however, it does not have permission to perform action 'peer/action' on the linked scope(s) '/subscriptions/xxxxx/resourceGroups/Customer-Prod-Net-RG/providers/Microsoft.Network/virtualNetworks/Customer-Prod-VNET'."

**Comment by amanohar** [comment]
@tahonen at this time cross tenant & subscription VNET peering is not supported.
