### ISSUE TITLE
az openshift create "DeploymentNotFound"

### ISSUE THREAD

**Issue by stianfro** [Azure/OpenShift#69]
Hi,

When running `az openshift create` we're getting a 404 "DeploymentNotFound" error.

```
# CLUSTER_NAME=int-az-ocp
# LOCATION=northeurope
# FQDN=$CLUSTER_NAME.$LOCATION.cloudapp.azure.com
$ az group create --name $CLUSTER_NAME --location $LOCATION
$ az openshift create --resource-group $CLUSTER_NAME --name $CLUSTER_NAME -l $LOCATION --fqdn $FQDN
Deployment failed. Correlation ID: _guid_. resources.DeploymentsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="DeploymentNotFound" Message="Deployment '_otherguid_' could not be found."
```

- Subscription is whitelisted
- Has been tried multiple times
- Tested on westeurope and northeurope

**Comment by julienstroheker** [comment]
Hi @stianfro 

Thanks for reporting this ! 

Can you validate if you have enough Cores available in your subscription for those regions ? 

I am seeing this happening on my side for you requests : 

```
Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 0, Additional requested: 36. Please read more about quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters.```

We are working on our side to provide more information to our customer when this happening.

**Comment by stianfro** [comment]
Hi @julienstroheker 

Seems likely that's the case then! I'll confirm it and close the issue when I have.

**Comment by stianfro** [comment]
@julienstroheker Core quota limits was indeed the problem here.

Would it be possible to add an option similar to "--compute-count" in `az openshift scale` to `az openshift create` ?

**Comment by julienstroheker** [comment]
@stianfro we do have the `--compute-count` or `-c` option available into `az openshift create`

You can check all the options by doing `az openshift create --help` 

Thanks

**Comment by stianfro** [comment]
@julienstroheker Perfect, then it's all good. I'll read through the options more thoroughly.
