### ISSUE TITLE
Unable to deploy OSBA to OSA

### ISSUE THREAD

**Issue by ms-jasondel** [Azure/OpenShift#72]
Following the instructions described here: https://github.com/Azure/open-service-broker-azure to deploy the Open Service Broker for Azure on OpenShift:

oc process -f https://raw.githubusercontent.com/Azure/open-service-broker-azure/master/contrib/openshift/osba-os-template.yaml \
-p ENVIRONMENT=AzurePublicCloud \
-p AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID \
-p AZURE_TENANT_ID=$AZURE_TENANT_ID \
-p AZURE_CLIENT_ID=$AZURE_CLIENT_ID \
-p AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET \
| oc create -f - 

...eventially **fails**:

secret/osba-redis created
secret/osba-open-service-broker-azure-auth created
secret/osba-open-service-broker-azure created
service/osba-redis created
service/osba-open-service-broker-azure created
persistentvolumeclaim/osba-redis-pv-claim created
deployment.extensions/osba-redis created
deployment.extensions/osba-open-service-broker-azure created
**Error from server (Forbidden): clusterservicebrokers.servicecatalog.k8s.io is forbidden: User "<my user name>" cannot create clusterservicebrokers.servicecatalog.k8s.io at the cluster scope: no RBAC policy matched**

Subsequently trying to run the svcat CLI to enumerate services gives a similar error:

svcat get brokers -n osba
Error: unable to list cluster-scoped brokers (clusterservicebrokers.servicecatalog.k8s.io is forbidden: User "<my user name>" cannot list clusterservicebrokers.servicecatalog.k8s.io at the cluster scope: no RBAC policy matched)

**Comment by delormej** [comment]
Note that following these instructions will work with ARO: https://github.com/Azure/open-service-broker-azure#openshift-project-template.  This can be closed.
