### ISSUE TITLE
Authentication error on Dashboard

### ISSUE THREAD

**Issue by borstibacon** [Azure/OpenShift#73]
Hi all,

i was just creating an OS cluster.
After browsing to the dashboard and logging on with my tenant account, i get the following error message:

"An authentication error occurred."

For test purpose I´ve granted the OC´s ServicePrincipal all Permissions on AAD and MS Graph.

Has anyone an idea, how to solve this problem?

Thanks!

Best regards,

René

**Comment by mohmdnofal** [comment]
did you follow this guide? https://github.com/Azure/OpenShift/blob/master/docs/aad-application-configuration.md 

note that the reply-urls must match the FQDN of the cluster.

**Comment by borstibacon** [comment]
Hi,

no. I just created the cluster.
During this process the AAD Application were created.

**Comment by amanohar** [comment]
@borstibacon can you try running the console in a private or Incognito browsing session and try logging in again?

Also, can you verify that reply URL is setup correctly for your AAD app? -> https://github.com/Azure/OpenShift/blob/master/docs/aad-application-configuration.md#verify--update-reply-urls-in-aad-app-using-the-portal

**Comment by borstibacon** [comment]
@amanohar 
Using incognito tab doesnt work.
App Registration is also correctly configured.

Still the same issue.

I will deploy a new OS cluster to test it again and to save consumption.
Thanks to all for the support.

**Comment by amanohar** [comment]
@borstibacon can you also confirm that your subscription is whitelisted to create OSA clusters?
