### ISSUE TITLE
AAD required-resource-access

### ISSUE THREAD

**Issue by jim-minter** [Azure/OpenShift#77]
@amanohar @julienstroheker 

We are currently setting up our AAD app as follows, the /docs/aad-application-configuration.md (and also CLI?) need to be updated:

```
az ad app create \
    ...
    --required-resource-accesses @- <<'EOF'
[
    {
      "resourceAppId": "00000003-0000-0000-c000-000000000000",
      "resourceAccess": [
        {
          "id": "5b567255-7703-4780-807c-7be8301ae99b",
          "type": "Role"
        },
        {
          "id": "37f7f235-527c-4136-accd-4a02d197296e",
          "type": "Scope"
        }
      ]
    }
]
EOF
```

Meaning of the magic numbers:
"00000003-0000-0000-c000-000000000000" -> microsoft graph
"5b567255-7703-4780-807c-7be8301ae99b" -> read all groups  # used by aad group sync
"37f7f235-527c-4136-accd-4a02d197296e" -> sign users in
"type": "Role" -> application permission
"type": "Scope" -> delegated permission

**Comment by jim-minter** [comment]
Hmm, now it turns out those permissions don't work for us: now we are going for:

```
    {
      "resourceAppId": "00000002-0000-0000-c000-000000000000",
      "resourceAccess": [
        {
          "id": "5778995a-e1bf-45b8-affa-663a9f3f4d04",
          "type": "Role"
        },
        {
          "id": "311a71cc-e848-46a1-bdf8-97ff7156d8e6",
          "type": "Scope"
        }
      ]
    }
```

"00000002-0000-0000-c000-000000000000" -> AAD Graph API
"5778995a-e1bf-45b8-affa-663a9f3f4d04" -> Read directory data
"311a71cc-e848-46a1-bdf8-97ff7156d8e6" -> Sign in and read user profile

**Comment by amanohar** [comment]
@jim-minter isn't think permission also needed for cluster admin role?:

> "5b567255-7703-4780-807c-7be8301ae99b" -> read all groups # used by aad group sync``

**Comment by rokukapsch** [comment]
Hi!

Is there a updated documentation out there, which lists all needed permissions on the AD?

Thanks and BR, Robert

**Comment by mohmdnofal** [comment]
we can just re-use the AKS AAD docs which should be sufficient
https://docs.microsoft.com/en-us/azure/aks/aad-integration

**Comment by amanohar** [comment]
@mohmdnofal no the AKS AAD app permissions are not the same as OSA AAD app permissions.
