### ISSUE TITLE
Add Azure File Storage Class to OSA

### ISSUE THREAD

**Issue by mohmdnofal** [Azure/OpenShift#78]
Please add support for Azure File storage class to OSA.

Only Azure Disk is Available
#oc get storageclass
NAME              PROVISIONER                AGE
azure (default)   kubernetes.io/azure-disk   19d

~Mo

**Comment by mohmdnofal** [comment]
The preference is to have the storage class tied to a storage account outside the cluster resource group so we decouple the storage from the cluster resources. this option was added in K8s 1.12 though, so not sure if it would be possible to backport to OS 3.11? 
https://github.com/kubernetes/kubernetes/pull/68117

**Comment by sakthi-vetrivel** [comment]
Closing this issue as it's gone stale. Please re-open if necessary.
