### ISSUE TITLE
cleanup: Service Principal (app) not deleted when OSA is removed

### ISSUE THREAD

**Issue by toniwillberg** [Azure/OpenShift#83]
Deleting OpenShift (OSA) seems to delete all services successfully but Service Principal / App Registration entries are left behind. 

When SP is created by the installer it would make sense to delete it when OSA is deleted.

**Comment by amanohar** [comment]
@toniwillberg application is created by the CLI as a convenience to the user and is not created by the service and therefore cannot be deleted by the service. User has the option to provide a pre-created application instead of having CLI create one for it.
