### ISSUE TITLE
Openshift web front doesn't listen on port 80

### ISSUE THREAD

**Issue by toniwillberg** [Azure/OpenShift#84]
After OSA is being deployed from command line, the output says this:
  "fqdn": "myclustername.westeurope.cloudapp.azure.com",

Copy & paste the address to browser and you will get "Can't reach this page".

The server is listening only on port 443, so https:// will fix the issue. Took me some time to figure out what's wrong.

Proposed solution: add a listener on port 80 and redirect user to port 443.

**Comment by amanohar** [comment]
@toniwillberg thanks for the feedback. I better fix is to return `https` suffixed in the `fqdn` returned by the service instead of redirecting from 80 to 443.

**Comment by sakthi-vetrivel** [comment]
Closing this issue as it's gone stale. Please re-open if necessary.
