### ISSUE TITLE
cluster creation fails, "password must contain at least 1 special character"

### ISSUE THREAD

**Issue by toniwillberg** [Azure/OpenShift#85]
This problem started to happen end of last week:

 az openshift create --resource-group $CLUSTER_NAME --name $CLUSTER_NAME -l $LOCATION --fqdn $FQDN
The password must contain at least 1 special character. paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application

If I provide Service Principal (AAD client app ID) the deployment works, but it creating new one automatically seems to fail.

**Comment by toniwillberg** [comment]
Adding parameter  --aad-client-app-secret with a proper password fixes the issue. Perhaps the default password is not random enough?

**Comment by sakthi-vetrivel** [comment]
Closing this issue as it's gone stale. Please re-open if necessary.
