### ISSUE TITLE
RBAC / external user authentication error

### ISSUE THREAD

**Issue by toniwillberg** [Azure/OpenShift#86]
Unable to login to OpenShift, error : error=access_denied&error_description=AADSTS650056%3a+Misconfigured+application

**Scenario:**
 I've deployed OpenShift cluster as myself (username@companydomain), and I am able to login as myself to OpenShift via web UI.

**What doesn't work:**
 Access OpenShift as other user from different domain (username@othercompany). 

 I have created a Role binding in OpenShift for external user (username@othercompany) as "Admin" in "Project1".

OpenShift UI gives error "An authentication error occurred" when the user tries to access it. (See attached screenshot)

Is this because the user is from different domain? Or do have I some other error in my setup?

URL of the error is:
 https://MYCLUSTERNAME.westeurope.cloudapp.azure.com/oauth2callback/Azure%20AD?error=access_denied&error_description=AADSTS650056%3a+Misconfigured+application.+This+could+be+due+to+one+of+the+following%3a+The+client+has+not+listed+any+permissions+for+%27AAD+Graph%27+in+the+requested+permissions+in+the+client%27s+application+registration.+Or%2c+The+admin+has+not+consented+in+the+tenant.+Or%2c+Check+the+application+identifier+in+the+request+to+ensure+it+matches+the+configured+client+application+identifier.+Please+contact+your+admin+to+fix+the+configuration+or+consent+on+behalf+of+the+tenant.+Client+app+ID%3a+039caeb9-2677-47c0-810b-5d985175af69.%0d%0aTrace+ID%3a+687d20a9-a703-4632-a3f0-ab871ec91200%0d%0aCorrelation+ID%3a+e00b3fc8-46f8-4e01-abe9-d71a5a754f89%0d%0aTimestamp%3a+2019-03-12+14%3a06%3a35Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d650056&state=Y3NyZj1xY2RPSXpxc2wzLXlvWVJqMGh2RnQ0TndEaDJrNjRDQXNaRjJFdTRNRGl3JnRoZW49JTJGb2F1dGglMkZhdXRob3JpemUlM0ZjbGllbnRfaWQlM0RvcGVuc2hpZnQtd2ViLWNvbnNvbGUlMjZyZXNwb25zZV90eXBlJTNEY29kZSUyNnN0YXRlJTNEZXlKMGFHVnVJam9pTDJOaGRHRnNiMmNpTENKdWIyNWpaU0k2SWpFMU5USXpPVEF5T0RJMU9URXRNalU0TVRnMk9UWTFPVFF4TmpreE9URTVNamt5TURrM05UZzBPREUzTkRnM05qSTBPVFF6T0RBNU5Ua3pPRFkyTVRNek56TXlOREk0TURFek5UY3lNemsyTnpnek1URTNNakUxTURJNUluMCUyNnJlZGlyZWN0X3VyaSUzRGh0dHBzJTI1M0ElMjUyRiUyNTJGdHdvc2E3Lndlc3RldXJvcGUuY2xvdWRhcHAuYXp1cmUuY29tJTI1MkZjb25zb2xlJTI1MkZvYXV0aA%3d%3d

![image](https://user-images.githubusercontent.com/1982933/54206667-6dae9880-44e1-11e9-922e-07162233f095.png)

**Comment by amanohar** [comment]
@toniwillberg, regarding:
>Access OpenShift as other user from different domain (username@othercompany).

Do you mean you are trying to login to the console with a user from a different AAD tenant aka domain? Each OSA cluster can be configured with only one AAD tenant today. This tenant is configured via the `authProfile` during cluster creation. 

OSA will not authenticate or authorize with an AAD tenant other than the one the cluster was created with.

**Comment by toniwillberg** [comment]
Ok just to clarify: there is no way to allow users from different domains to use OSA?

**Comment by amanohar** [comment]
@toniwillberg at this time only one AAD tenant is supported. As long as users exist in the same tenant the cluster was configured with it will work. 

Can you confirm if the user(s) exist in the tenant that you created the cluster with?

**Comment by toniwillberg** [comment]
The user used to create the cluster is from the same tenant, and he (me) is able to log in.

Issue was that external user (from different) tenant was not able to log in. This was just a test to understand the limits, not a showstopper at this time.

**Comment by sakthi-vetrivel** [comment]
Closing this issue as it's gone stale. Please re-open if necessary.
