### ISSUE TITLE
Input/output error azure disk

### ISSUE THREAD

**Issue by mjudeikis** [Azure/OpenShift#89]
When creating Statefulset with Azure disk PVC template kubelet loses reference to azure disk due to mountpoint letter changes.

Issue description: https://github.com/openshift/openshift-azure/issues/1278

This is an intermediate issue and is not happening all the time. 

/cc @amanohar @jim-minter

**Comment by jim-minter** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1691932

**Comment by mjudeikis** [comment]
upstream issue: https://github.com/kubernetes/kubernetes/issues/75619

**Comment by sakthi-vetrivel** [comment]
Closing this issue as it's gone stale. Please re-open if necessary.
