### ISSUE TITLE
ResourcePurchaseCanceling error

### ISSUE THREAD

**Issue by jim-minter** [Azure/OpenShift#91]
Deployment failed. Correlation ID: c5a3ff12-9e23-48bc-945d-2ddc646f4151. unable to create managed app. error: managedapplications.ApplicationsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ResourcePurchaseCanceling" Message="The resource 'OS_jminterprod_jminterprod_eastus' with the id 'Microsoft.Solutions/applications/OS_jminterprod_jminterprod_eastus' has a previous order being canceled. Please try after some time or create resource with different name. "

**Comment by jim-minter** [comment]
@amanohar saw this error in prod, have also seen something similar on dev clusters.  Please can you advise what we should do?

Time: approximately 26/3/19 15:20 UTC
Subscription ID: 225e02bc-43d0-43d1-a01a-17e584a4ef69
RG/OSA name: jminterprod
Correlation ID: c5a3ff12-9e23-48bc-945d-2ddc646f4151

**Comment by jim-minter** [comment]
Interesting: the error in prod is on a Microsoft.Solutions/applications resource - in dev, I've seen it or something similar on scale sets.

**Comment by sozercan** [comment]
Closing this since this is an e2e only error due to marketplace timeout.
