### ISSUE TITLE
Adding users as customer-admin

### ISSUE THREAD

**Issue by cmendible** [Azure/OpenShift#92]
Hi @kwoodson you mention in #87 that there is an AAD group ID specified at install time. Both the CLI and the limited portal support lack of such parameter. 

Any clue on how can we add AAD users to a group and therefore make them customer-admins?

Also the default behavior, after instalation, seems to be that any user with access to our AAD is able to login an create project in the OSA clusters.

**Comment by amanohar** [comment]
@cmendible CLI has not been updated yet to enable customer admin feature (will be done soon). However, in the meantime you can use ARM template to deploy an OSA cluster enabled with customer admin role.

**CLI commands to create OSA cluster using ARM CLI:**

```
az login -t <TENANT_ID>
az account set --subscription <SUB_ID>
az group create -n <RG_NAME> -l "<REGION_NAME>"
az group deployment create --resource-group "<RG_NAME>"  --template-file <TEMPLATE_FILE>
```

Replace `<UPDATE>` with the right value, save the file and reference it in the `--template-file` flag in the command above. 

**`customerAdminGroupId`** is the new field for customer admin role. Set it to the GUID of AAD distribution group that contains admin users who will manage the OSA cluster.

**Sample ARM template:**
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
      {
        "location": "<UPDATE>",
        "name": "<UPDATE>",
        "type": "Microsoft.ContainerService/openShiftManagedClusters",
        "apiVersion": "2018-09-30-preview",
        "properties": {
          "openShiftVersion": "v3.11",
          "fqdn": "<UPDATE>.<UPDATE_REGION_NAME>.cloudapp.azure.com",
          "networkProfile": {
            "vnetCidr": "10.0.0.0/8"
          },
          "authProfile": {
            "identityProviders": [
              {
                "name": "Azure AD",
                "provider": {
                  "kind": "AADIdentityProvider",
                  "clientId": "<UPDATE>",
                  "secret": "<UPDATE>",
                  "tenantId": "<UPDATE>",
                  "customerAdminGroupId": "<UPDATE>"
                }
              }
            ]
          },
          "masterPoolProfile": {
            "name": "master",
            "count": 3,
            "subnetCidr": "10.0.0.0/24",
            "vmSize": "Standard_D4s_v3",
            "osType": "Linux"
          },
          "agentPoolProfiles": [
            {
              "role": "compute",
              "name": "compute",
              "count": 1,
              "subnetCidr": "10.0.0.0/24",
              "vmSize": "Standard_D4s_v3",
              "osType": "Linux"
            },
            {
              "role": "infra",
              "name": "infra",
              "count": 2,
              "subnetCidr": "10.0.0.0/24",
              "vmSize": "Standard_D4s_v3",
              "osType": "Linux"
            }
          ],
          "routerProfiles": [
            {
              "name": "default"
            }
          ]
        }
      }
    ]
  }
```

cc: @JackQuincy

**Comment by cmendible** [comment]
I can confirm that deployment using the template by @amanohar works adding the `customerAdminGroupId` 

But this doesn't prevent that any user with access to the associated AAD can login and create projects inside the cluster.  Can you confirm this is the default behavior?  How can we remediate this?

Thanks!

**Comment by amanohar** [comment]
@cmendible In order to restrict the AAD users that can log to the cluster via AAD app configuration: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users

**Comment by cmendible** [comment]
@amanohar perfect that did the trick! Perhaps the docs should be updated with that pointer. I'm closing this issue now. Thanks!

**Comment by amanohar** [comment]
Thanks @cmendible for confirming. I opened a docs issue to track this.
