### ISSUE TITLE
Document how to retrict AAD users' access to OSA cluster

### ISSUE THREAD

**Issue by amanohar** [Azure/OpenShift#94]
By default all users in an AAD tenant can access OSA cluster. In order to restrict the AAD users that can log to the cluster via AAD app configuration: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users

Add documentation for this configuration.

**Comment by TylerMSFT** [comment]
I've added this to the documentation backlog.
#please-close

**Comment by TylerMSFT** [comment]
Please assign to JimZim. I am no longer on OpenShift.
TFS 1495807, assigned to JimZim, is tracking this.

**Comment by TylerMSFT** [comment]
#reassign:jimzim

**Comment by TylerMSFT** [comment]
#reassign:jimzim
