### ISSUE TITLE
CLI generated cluster AAD wrong permissions

### ISSUE THREAD

**Issue by mjudeikis** [Azure/OpenShift#95]
Created a cluster with new CLI and AAD got pre-created:
![image](https://user-images.githubusercontent.com/3225744/55659409-61281200-57f9-11e9-8868-4a7de0d76ec7.png)

But we need:
![image](https://user-images.githubusercontent.com/3225744/55659437-89177580-57f9-11e9-904e-1b0db1634cbd.png)

We lack "Read directory data". 

/cc @amanohar @jim-minter I think this is quite urgent for summit labs :/

**Comment by mjudeikis** [comment]
Related to this:
Current CLI still generates wrong permissions:
![image](https://user-images.githubusercontent.com/3225744/55957900-59d09080-5c5f-11e9-98ae-03a2ec361756.png)

in addition after TLS work in 3.2 there is some misconfiguration into how AAD app is configured:
![image](https://user-images.githubusercontent.com/3225744/55957889-50dfbf00-5c5f-11e9-9d47-0819ac589de5.png)

Callback url is: `https://mjudeikissummit9.eastus.cloudapp.azure.com/oauth2callback/Azure%20AD`
But console is exposed via: `https://openshift.a6ee8405c4c14c23ac91.eastus.azmosa.io`

Callback url in AAD should publicHostname value, not internal FQDN: `https://openshift.a6ee8405c4c14c23ac91.eastus.azmosa.io/oauth2callback/Azure%20AD`

/cc @amanohar @jim-minter

**Comment by amanohar** [comment]
This has been fixed in new CLI versions.
