### ISSUE TITLE
'whatever' az bug

### ISSUE THREAD

**Issue by jim-minter** [Azure/OpenShift#99]
@julienstroheker I think the following must be incomplete code / a logic bug?

https://github.com/Azure/azure-cli/blob/3bf3b3256e4678c8dceb7245279e67f05bbfa360/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py#L2297

**Comment by julienstroheker** [comment]
This was here when using previous api version. It is now removed.
